<?php
/**
 * Implements hook_node_info()
 */
//function tours_node_info() {
//    return array(
//        'tours' => array(
//            'name' => t('Tours'),
//            'base' => 'tours',
//            'description' => t('You can Addyou Tour details'),
//            'has_title' => TRUE,
//            'title_label' => t('Title')
//         )
//    );
//}
function tours_menu()
{
   $items['tours/add']=array(//to creating the Url
       'title' => 'tours',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tours_form'),
       'access callback' => TRUE,
   );
   return $items;
}
function tours_form($form,&$form_submit)
{
    
    $form['title']=array(
        '#title'=>t('Title'),
        '#type'=>'textfield',
        '#required' => TRUE
    );
    $form['description']=array(
        '#title'=>t('Description'),
        '#type'=>'textarea',
        '#required' => TRUE
    );
    $form['startdate']=array(
        '#title'=>t('Start Date'),
        '#type'=>'textfield',
        '#required' => TRUE
    );
    $form['enddate']=array(
        '#title'=>t('End Date'),
        '#type'=>'textfield',
        '#required' => TRUE
    );
    $form['volume']=array(
        '#title'=>t('Volume'),
        '#type'=>'textfield',
        '#required' => TRUE
    );
    $form['submit'] = array(
        '#value' => 'Submit',
        '#type' => 'submit',
        '#name' => 'submit'
    );
    print_r(node_load(11));
    return $form;
}

function tours_form_submit($form,&$form_state)
{
//    die(var_dump($form_state));
    global $user;
    $node= new stdClass();
    $node->title="tours";
    $node->type="tour";
    node_object_prepare($node); 
    $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
    $node->uid = $user->uid; 
    $node->status = 1; //(1 or 0): published or not
    $node->promote = 0; //(1 or 0): promoted to front page
    $node->comment = 1; // 0 = comments disabled, 1 = read only, 2 = read/write
    // Term reference (taxonomy) field
//  $node->field_product_tid[$node->language][]['tid'] = $form_state['values']['a taxonomy term id'];
//
//  // Entity reference field
//  $node->field_customer_nid[$node->language][] = array(
//    'target_id' => $form_state['values']['entity id'],
//    'target_type' => 'node',
//  );
  // 'node' is default,
  // Other possible values are "user" and  "taxonomy_term" 
$node->field_start_date['und'][0]['value'] = $form_state['values']['startdate'];
$node->field_finish_date['und'][0]['value'] = $form_state['values']['enddate'];
$node->field_volume['und'][0]['value'] = $form_state['values']['volume'];

  $node = node_submit($node); // Prepare node for saving
  node_save($node);
  //drupal_set_message( "Node with nid " . $node->nid . " saved!\n");
  $form_state['redirect']  = '/';
}
