<?php
function tours_menu()
{
   $item['formtour']=array(
       'title' => 'Tour',
       'page callback' => 'drupal_get_form',
       'page_arguments' => array('tours_form'),
       'access callback' => TRUE,
   );
   return $items;
}
function tours_form($form,&$form_submit)
{
    $form['title']=array(
        '#title'=>t('Title'),
        '#type'=>'textfield',
        '#required' => TRUE
    );
    $form['description']=array(
        '#title'=>t('Description'),
        '#type'=>'textarea',
        '#required' => TRUE
    );
    $form['startdate']=array(
        '#title'=>t('Start Date'),
        '#type'=>'date',
        '#required' => TRUE
    );
    $form['enddate']=array(
        '#title'=>t('End Date'),
        '#type'=>'date',
        '#required' => TRUE
    );
    $form['volume']=array(
        '#title'=>t('Volume'),
        '#type'=>'textfield',
        '#required' => TRUE
    );
    
    
}
